global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fintech-app'
    static_configs:
      - targets: ['fintech-app-service:80']  # Replace with your service name and port
    metrics_path: '/metrics'  # Adjust if your application exposes metrics at a different path

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_node_name]
        regex: .*

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_namespace]
        regex: default  # Adjust if your pods are in a different namespace
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels: [__meta_kubernetes_pod_name]
        target_label: instance
      - action: drop
        source_labels: [__meta_kubernetes_pod_container_name]
        regex: .*-init  # Exclude init containers if necessary